### ISSUE TITLE
Streaming content of multipart/form-data requests server-side

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5511]
|<img alt="EDevil's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| EDevil reported|
|-|-|
|Trac ID|trac#5511|
|Type|enhancement|
|Created|2012-03-06 23:26:27Z|

Twisted is missing a mechanism to handle large multipart/form-data POST requests in a streaming fashion. The current twisted.web implementation loads the entire body into memory in order to parse it with the cgi module. Being able to access the body of the request as it is being read can also be useful in cases where the processing can start before the file is completely transferred.

Something in the lines of: http://debuggable.com/posts/streaming-file-uploads-with-node-js:4ac094b2-b6c8-4a7f-bd07-28accbdd56cb

<details><summary>Searchable metadata</summary>

```
trac-id__5511 5511
type__enhancement enhancement
reporter__EDevil EDevil
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__streamming__multipart streamming, multipart
time__1331076387000000 1331076387000000
changetime__1364212921000000 1364212921000000
version__None None
owner__ 
cc__EDevil
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

I'm not sure how different this is from [#4688](https://github.com/twisted/twisted/issues/4688).  Maybe it's just a thin layer on top of the functionality provided by [#4688](https://github.com/twisted/twisted/issues/4688) for parsing the request body into a more structured form representing a form post (including a stream for files that are part of the post).

**Comment by twisted-trac** [comment]
|<img alt="EDevil's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|EDevil commented|
|-|-|

Yes, that's why I filed a different issue. I think I can access the data being uploaded now by redefining some methods, as you said on the IRC channel. Being able to do this without messing around with Twisted internals would be nice, and I guess that is [#4688](https://github.com/twisted/twisted/issues/4688). But in the case of multipart requests there still is the issue of parsing these structures in a streaming fashion, which cgi.parse_multipart does not do and cgi.FieldStorage requires a file to read the data from.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Relatedly, the multipart/form-data parser on Python 3 is broken (<http://bugs.python.org/issue12411>).  This is perhaps another reason to implement our own.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_4"></a>|@itamarst commented|
|-|-|

I believe the Python bug above has been fixed. Also, `email.FeedParser` may be the way to go, given that it has incremental parsing.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

Or Parsley.

**Comment by hansingt** [comment]
This issue still persists and hit me just today. Is there any progress about this since the last 11 (!) years?

**Comment by glyph** [comment]
@hansingt there are various hacky workarounds but the fundamental problem is still around :).  Do you have interest in collaborating on a proper fix?

**Comment by glyph** [comment]
(See also: #4688 #5152 )

**Comment by hansingt** [comment]
> @hansingt there are various hacky workarounds but the fundamental problem is still around :). Do you have interest in collaborating on a proper fix?

@glyph: Thanks for the reply. Which kind of hacky workarounds?

Our main problem is, that we tried to upload a large file (5GiB), as part of a `multipart/form-data`  request and the implementation of twisted is reading and copying the file multiple times, wich resulted in ~25GiB peak RAM usage. We identified the problem in the Code around [twisted.web.http#L1017](https://github.com/twisted/twisted/blob/trunk/src/twisted/web/http.py#L1017), which is reading and decoding the whole request, which results in multiple copies of the request being kept in-memory.

I think, this is done to extract the metadata parts of the multipart/form-data from the request.

My Idea would be, to implement this in a streaming manner, instead of reading and decoding the whole request. But I'm not sure, how we can replace the `twisted.web.http.Request` class with our own implementation. Would this be possible at all?

If I find a workaround for this, I'd be happy to send a pull request to integrate it upstream.

**Comment by adiroiban** [comment]
Hi Torben

see also https://github.com/twisted/twisted/issues/5379 and https://github.com/twisted/twisted/issues/3621 and https://github.com/twisted/twisted/issues/6928 ... there are a lot of related issued :(

Implementing streaming for HTTP server-side requests required significant changes 

One of the big problems (there are more), is that Twisted web resource traversal is done after all the request was received.

It looks like there were various atempts, but there was no concensus in terms of API.

I am happy to continue the work on Twisted web streaming support, as for a long time I am using a fork of `twisted.web`
I need at least another developer to review and provide feedback.
I have requested for feedback in [Feb 2014](http://twistedmatrix.com/pipermail/twisted-python/2014-February/028069.html) ... no feedback so far.

I know that [Expect: 100-continue](https://github.com/twisted/twisted/issues/6928) functionality is not that exciting... but I think this should be the starting point.

It will allow supporting RFC 2616 - 8.2.3 and will make it easier to focus on the resource traversal part... before looking at content streaming.

**Comment by glyph** [comment]
> @glyph: Thanks for the reply. Which kind of hacky workarounds?

The hacky workaround is to write your own custom *request factory* rather than a custom resource, override `allHeadersReceived`, and do request traversal in there rather than doing traversal (as @adiroiban points out) in `requestReceived`.

**Comment by glyph** [comment]
Note that custom request factories *are* supported by the twisted.web public API, it's just in a slightly awkward corner: https://docs.twistedmatrix.com/en/stable/api/twisted.web.server.Site.html#requestFactory
